// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package pgsql

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AssetsOpStatus string

const (
	AssetsOpStatusActive   AssetsOpStatus = "active"
	AssetsOpStatusInactive AssetsOpStatus = "inactive"
	AssetsOpStatusDisposed AssetsOpStatus = "disposed"
)

func (e *AssetsOpStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetsOpStatus(s)
	case string:
		*e = AssetsOpStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetsOpStatus: %T", src)
	}
	return nil
}

type NullAssetsOpStatus struct {
	AssetsOpStatus AssetsOpStatus
	Valid          bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetsOpStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetsOpStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetsOpStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetsOpStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.AssetsOpStatus, nil
}

type AssetsStages string

const (
	AssetsStages1  AssetsStages = "1"
	AssetsStages12 AssetsStages = "1-2"
	AssetsStages2  AssetsStages = "2"
	AssetsStages23 AssetsStages = "2-3"
	AssetsStages3  AssetsStages = "3"
	AssetsStages4  AssetsStages = "4"
)

func (e *AssetsStages) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetsStages(s)
	case string:
		*e = AssetsStages(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetsStages: %T", src)
	}
	return nil
}

type NullAssetsStages struct {
	AssetsStages AssetsStages
	Valid        bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetsStages) Scan(value interface{}) error {
	if value == nil {
		ns.AssetsStages, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetsStages.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetsStages) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.AssetsStages, nil
}

type AssetsClrSection struct {
	ID           int64          `json:"id"`
	Make         string         `json:"make"`
	SerialNumber string         `json:"serial_number"`
	Mawp         int32          `json:"mawp"`
	NumTubes     sql.NullInt32  `json:"num_tubes"`
	NumRows      sql.NullInt32  `json:"num_rows"`
	Passes       sql.NullInt32  `json:"passes"`
	OpStatus     AssetsOpStatus `json:"op_status"`
	CreatedAt    time.Time      `json:"created_at"`
	ModifiedAt   time.Time      `json:"modified_at"`
}

type AssetsClrpkg struct {
	ID              int64         `json:"id"`
	UnitNumber      string        `json:"unit_number"`
	Size            string        `json:"Size"`
	OpStatus        string        `json:"op_status"`
	ComStatus       string        `json:"com_status"`
	CurrentLocation string        `json:"current_location"`
	DriverID        sql.NullInt32 `json:"driver_id"`
	CoolerID        sql.NullInt32 `json:"cooler_id"`
	CreatedAt       time.Time     `json:"created_at"`
	ModifiedAt      time.Time     `json:"modified_at"`
}

type AssetsCmppkg struct {
	ID              int64         `json:"id"`
	UnitNumber      string        `json:"unit_number"`
	Stages          string        `json:"stages"`
	OpStatus        string        `json:"op_status"`
	ComStatus       string        `json:"com_status"`
	CurrentLocation string        `json:"current_location"`
	DriverID        sql.NullInt32 `json:"driver_id"`
	CompressorID    sql.NullInt32 `json:"compressor_id"`
	CoolerID        sql.NullInt32 `json:"cooler_id"`
	VesselID        sql.NullInt32 `json:"vessel_id"`
	DrawingRef      interface{}   `json:"drawing_ref"`
	Bom             sql.NullInt32 `json:"bom"`
	CreatedAt       time.Time     `json:"created_at"`
	ModifiedAt      time.Time     `json:"modified_at"`
}

type AssetsCompressor struct {
	ID           int64          `json:"id"`
	Make         string         `json:"make"`
	Model        string         `json:"model"`
	SerialNumber string         `json:"serial_number"`
	OpStatus     AssetsOpStatus `json:"op_status"`
	CylinderID   sql.NullInt32  `json:"cylinder_id"`
	CreatedAt    time.Time      `json:"created_at"`
	ModifiedAt   time.Time      `json:"modified_at"`
}

type AssetsCooler struct {
	ID         int64          `json:"id"`
	Make       string         `json:"make"`
	Model      string         `json:"model"`
	JobNumber  string         `json:"job_number"`
	OpStatus   AssetsOpStatus `json:"op_status"`
	SectionID  sql.NullInt32  `json:"section_id"`
	CreatedAt  time.Time      `json:"created_at"`
	ModifiedAt time.Time      `json:"modified_at"`
}

type AssetsCylinder struct {
	ID           int64          `json:"id"`
	Make         string         `json:"make"`
	Model        string         `json:"model"`
	Mawp         int32          `json:"mawp"`
	SerialNumber string         `json:"serial_number"`
	OpStatus     AssetsOpStatus `json:"op_status"`
	CreatedAt    time.Time      `json:"created_at"`
	ModifiedAt   time.Time      `json:"modified_at"`
}

type AssetsDriver struct {
	ID         int64         `json:"id"`
	EngineID   sql.NullInt32 `json:"engine_id"`
	MotorID    sql.NullInt32 `json:"motor_id"`
	CreatedAt  time.Time     `json:"created_at"`
	ModifiedAt time.Time     `json:"modified_at"`
}

type AssetsEngine struct {
	ID           int64          `json:"id"`
	Make         string         `json:"make"`
	Model        string         `json:"model"`
	SerialNumber string         `json:"serial_number"`
	OpStatus     AssetsOpStatus `json:"op_status"`
	CreatedAt    time.Time      `json:"created_at"`
	ModifiedAt   time.Time      `json:"modified_at"`
}

type AssetsMotor struct {
	ID           int64          `json:"id"`
	Make         string         `json:"make"`
	Model        string         `json:"model"`
	SerialNumber string         `json:"serial_number"`
	OpStatus     AssetsOpStatus `json:"op_status"`
	CreatedAt    time.Time      `json:"created_at"`
	ModifiedAt   time.Time      `json:"modified_at"`
}

type AssetsPlsBottle struct {
	ID           int64          `json:"id"`
	SerialNumber string         `json:"serial_number"`
	Mawp         int32          `json:"mawp"`
	Diameter     sql.NullInt32  `json:"diameter"`
	Length       sql.NullInt32  `json:"length"`
	DrawingRef   interface{}    `json:"drawing_ref"`
	OpStatus     AssetsOpStatus `json:"op_status"`
	CreatedAt    time.Time      `json:"created_at"`
	ModifiedAt   time.Time      `json:"modified_at"`
	UnitID       sql.NullInt32  `json:"unit_id"`
}

type AssetsScrubber struct {
	ID           int64          `json:"id"`
	SerialNumber string         `json:"serial_number"`
	Mawp         int32          `json:"mawp"`
	Diameter     sql.NullInt32  `json:"diameter"`
	Length       sql.NullInt32  `json:"length"`
	DrawingRef   interface{}    `json:"drawing_ref"`
	OpStatus     AssetsOpStatus `json:"op_status"`
	CreatedAt    time.Time      `json:"created_at"`
	ModifiedAt   time.Time      `json:"modified_at"`
}

type AssetsVessel struct {
	ID          int64         `json:"id"`
	ScrubberID  sql.NullInt32 `json:"scrubber_id"`
	PlsBottleID sql.NullInt32 `json:"pls_bottle_id"`
	UnitID      sql.NullInt32 `json:"unit_id"`
}
