// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package pgsql

import (
	"context"
)

type Querier interface {
	CmpPkgChgComp(ctx context.Context, arg CmpPkgChgCompParams) (AssetsCmppkg, error)
	CmpPkgChgDriver(ctx context.Context, arg CmpPkgChgDriverParams) (AssetsCmppkg, error)
	CreateCmpPkg(ctx context.Context, arg CreateCmpPkgParams) (AssetsCmppkg, error)
	DeleteCmpPkg(ctx context.Context, id int64) error
	GetCmpPkgByID(ctx context.Context, id int64) (AssetsCmppkg, error)
	GetCmpPkgByUnitNumber(ctx context.Context, unitNumber string) (AssetsCmppkg, error)
	GetCmpPkgs(ctx context.Context) ([]AssetsCmppkg, error)
	GetCmpPkgsByEngine(ctx context.Context, arg GetCmpPkgsByEngineParams) ([]GetCmpPkgsByEngineRow, error)
	GetCmpPkgsByStages(ctx context.Context, stages string) ([]AssetsCmppkg, error)
}

var _ Querier = (*Queries)(nil)
